[package]
name = "library"
version.workspace = true
edition.workspace = true

[dependencies]
actix = { workspace = true }
actix-rt = { workspace = true }
actix-utils = { workspace = true }
actix-web = { workspace = true }
actix-web-actors = { workspace = true }
actix-web-lab = { workspace = true }
anyhow = { workspace = true }
arraygen = { workspace = true }
async-graphql = { workspace = true, features = ["chrono"] }
async-graphql-actix-web = { workspace = true }
base64-url = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
cron = { workspace = true }
fluent-templates = { workspace = true, features = ["handlebars"] }
futures = { workspace = true }
futures-util = { workspace = true }
image = { workspace = true, features=["webp-encoder"] }
infer = { workspace = true }
lettre = { workspace = true }
nanoid = { workspace = true }
parking_lot = { workspace = true }
pasetolib = { package = "paseto", version = "2.0.2+1.0.3" }
pin-project = { workspace = true }
rand = { workspace = true }
rusoto_core = { workspace = true }
rusoto_s3 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json  = { workspace = true, features = ["preserve_order", "raw_value"] }
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "time", "chrono", "json"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
unic-langid = { workspace = true }
user-agent-parser = { workspace = true }
xsalsa20poly1305 = { workspace = true }

config = { workspace = true }
macros = { workspace = true }
